### ISSUE TITLE
Demo does not run

### ISSUE THREAD

**Issue by jjdestef3** [jean79/yested_fw#33]
After running mvn install from the terminal and opening index.html in a browser (from Intellij) I get the following error in the js console:

Uncaught Error: Error loading module 'Yested-tests'. Its dependency 'kotlin-test' was not found. Please, check whether 'kotlin-test' is loaded prior to 'Yested-tests'.
    at Yested-tests.js:8

Thanks

**Comment by epabst** [comment]
@jean79 please ratify.

**Comment by epabst** [comment]
Fixed.

**Comment by epabst** [comment]
@jjdestef3 thank you for letting us know! :)
