### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by augustbering** [jean79/yested_fw#42]
Hi, this looks like a great framework! However, I can't build it... I get something like the below when I try, it seems for some reason kotlin tries to use the jvm backend instead of js but I have no idea why and I'm not really friends with maven...

mvn install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.yested:Yested:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jar-plugin @ line 248, column 21
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.sonatype.plugins:nexus-staging-maven-plugin @ line 296, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 248, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 175, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Yested Framework 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Yested ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/august/dev/yested_fw/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Yested ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-dependency-plugin:3.0.1:unpack-dependencies (unpack-dependencies) @ Yested ---
[INFO] org.jetbrains.kotlin:kotlin-stdlib-js:jar:1.1.60 already exists in destination.
[INFO] 
[INFO] --- kotlin-maven-plugin:1.1.60:js (js) @ Yested ---
[WARNING] Module "kotlin" is defined in more than one file
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/htmlbind.kt: (76, 110) Unchecked cast: T? to T
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/htmlbind.kt: (115, 46) Parameter 'index' is never used, could be renamed to _
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/properties/properties.kt: (109, 49) Parameter 'old' is never used, could be renamed to _
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/properties/properties.kt: (110, 21) Parameter 'old' is never used, could be renamed to _
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/properties/properties.kt: (420, 42) Name shadowed: comparator
[WARNING] /home/august/dev/yested_fw/src/main/kotlin/net/yested/ext/jquery/router.kt: (34, 23) Parameter 'newValue' is never used, could be renamed to _
[INFO] 
[INFO] --- kotlin-maven-plugin:1.1.60:compile (compile) @ Yested ---
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (4, 15) Unresolved reference: browser
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (5, 15) Unresolved reference: dom
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (7, 10) Unresolved reference: HTMLElement
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (8, 47) The boolean literal does not conform to the expected type Boolean
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (8, 62) Unresolved reference: HTMLElement
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (8, 95) Unresolved reference: Unit
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (9, 21) Unresolved reference: document
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (10, 9) Type mismatch: inferred type is java.lang.Boolean but kotlin.Boolean was expected
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (10, 39) Type mismatch: inferred type is T but Node! was expected
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (11, 11) Unresolved reference: let
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (11, 25) Reference has a nullable type '(T.() -> [ERROR : Unit])?', use explicit '?.invoke()' to make a function-like call instead
[ERROR] /home/august/dev/yested_fw/src/main/kotlin/net/yested/core/html/html.kt: (12, 9) Unresolved reference: !

**Comment by epabst** [comment]
It looks like somehow you're using kotlin 1.1.60 when this project is set up for kotlin 1.1.4.  I'm not sure if that's the issue...

**Comment by augustbering** [comment]
Thank you, yes, for some reason it doesn't work with 1.1.60. 
1.1.4 compiles

**Comment by epabst** [comment]
@augustbering I tried 1.1.60 and it worked just fine.  I wonder if you have a corrupt kotlin-stdlib-js.jar.  Consider deleting ~/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-js and retrying it.

**Comment by epabst** [comment]
My fixes include eliminating almost all warnings.
