### ISSUE TITLE
QUnit.module is not a function

### ISSUE THREAD

**Issue by lincoln310** [jean79/yested_fw#46]
I built the target, and right clicked on the index.html, and opened it in chrome, but nothing shows up.
Then i found this in debug console:
kotlin-test.js:442 Uncaught TypeError: QUnit.module is not a function
    at QUnitAdapter.suite (kotlin-test.js:442)
    at suite (kotlin-test.js:370)
    at Yested-tests.js:2510
    at Yested-tests.js:2681

**Comment by epabst** [comment]
Confirmed.
